config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bookings
  resources :reports
  resources :habits
  resources :exams
  resources :medical_centers
  resources :recipes
  resources :users
  get "nosotros", to: "pages#nosotros"
  get "contacto", to: "pages#contacto"
  get "home2", to: "pages#home2"
  get "mi_salud", to: "pages#mi_salud"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  validates :start_time, :name, presence: true

end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :user
  validates :date, :name, :place, presence: true
  has_one_attached :photo
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  validates :habit_type, :quantity, :frequency, presence: true
  validates :habit_type, uniqueness: { scope: :user_id,
    message: "Ya existe este habito" }
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # siempre hacer asociaciones y validaciones antes del seed
  belongs_to :user
  validates :date, :doctor_name, presence: true
  has_one_attached :photo
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  validates :title, :date, :category, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # estas son las asociaciones
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :habits, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[address latitude longitude name last_name weight height date_of_birth gender phone_number blood_group blood_type photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[address latitude longitude name last_name weight height date_of_birth gender phone_number blood_group blood_type photo])
  end

  def after_sign_in_path_for(resource)
    exams_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings

    # Scope your query to the dates being shown:
    start_date = params.fetch(:start_time, Date.today).to_date

    # For a monthly view:
    @bookings = Booking.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)

  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:name, :start_time, :details, :address)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :exam_id, only: %i[show edit update destroy]
  def index
    @exams = current_user.exams.order(:created_at)
  end

  def show
  end

  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(exam_params)
    @exam.user = current_user
    if @exam.save
      redirect_to exams_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @exam.update(exam_params)
    redirect_to exam_path(@exam)
  end

  def destroy
    @exam.destroy
    redirect_to exams_path, status: :see_other
  end

  private

  def exam_params
    params.require(:exam).permit(:name, :date, :place)
  end

  def exam_id
    @exam = Exam.find(params[:id])
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :find_habit, only: %i[show edit destroy]

  def index
    @habits = current_user.habits
  end

  def new
    @habit = Habit.new
  end

  def show
  end

  def create
    @habit = Habit.new(habit_params)
    @habit.user = current_user
    if @habit.save
      redirect_to habits_path
    else
      render :new
    end
  end

  def update
    @habit = Habit.find(params[:id])
    @habit.update(habit_params)
    redirect_to habit_path(@habit)
  end

  def destroy
    @habit.destroy
    redirect_to habits_path, status: :see_other
  end

  private

  def find_habit
    @habit = Habit.find(params[:id])
  end

  def habit_params
    params.require(:habit).permit(:habit_type, :quantity, :frequency)
  end
end

app/controllers/medical_centers_controller.rb
class MedicalCentersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home nosotros mi_salud]
  # layout "layout_aplication", only: [:home]

  def index
  end

  def home
  end

  def contacto
  end

  def nosotros
  end

  def mi_salud
  end

  def home2
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: %i[show edit destroy update]
  def index
    @recipes = current_user.recipes
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipes_path
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:date, :doctor_name, :photo)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  def index
    @reports = current_user.reports
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user
    if @report.save
      redirect_to reports_path
    else
      render :new
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report.update(report_params)
    redirect_to report_path(@report)
  end

  def destroy
    @report.destroy
    redirect_to reports_path, status: :see_other
  end

  private

  def report_params
    params.require(:report).permit(:title, :date, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Bookings Homepage</h1>
<div>
  <%= month_calendar(events: @bookings) do |name, bookings| %>
    <%= name %>

    <% bookings.each do |booking| %>
      <div class="booking">
        <p><%= booking.name %></p>
      </div>
    <% end %>
  <% end %>

</div>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <div class="contenedor py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-110">
        <div class="col-lg">
          <div class="card shadow-2-strong" style="border-radius: 0.5rem;">
            <div class="card-body p-5 text-center " style="box-shadow: 3px 3px 3px 1px rgba(0, 0, 0, 0.4); border-radius: 8px 8px 8px 8px;">

              <h3 class="mb-5">Nuevo booking</h3>

              <div class="form-outline mb-4">
              <%= f.input :name, class: "form-control form-control-lg" %>
              </div>

              <div class="form-outline mb-4">
              <%= f.input :start_time, class:"form-control form-control-lg" %>
              </div>

              <div class="form-outline mb-4">
              <%=  f.input :details, class: "form-control form-control-lg" %>
              </div>

              <div class="form-outline mb-4">
              <%=  f.input :address, class: "form-control form-control-lg" %>
              </div>

                <%= f.button :submit, "Crear", class:"btn btn-primary btn-lg btn-block mt-3" %>
              <hr class="my-4">

            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/bookings/show.html.erb
<div class= "contenedor mt-5 mb-5">
  <div class="card-product">
    <%= cl_image_tag @product.photo.key, class: "imagen", height: 350, crop: :fill %>
    <div class="card-product-infos">
      <h1 style="color: black;"><%= @product.name  %></h1>
        <h2 style="color: black;"><%= @product.price  %> ARS </h2>
        <p style="color: black;"><%= @product.details %></p>
        <a href="#" class="btn btn-primary">Comprar</a>
        <div class= "card-product-infos" >
          <% if @product.user_id == current_user.id %>
          <%= link_to "Delete", product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Estas seguro?"}, class: "btn btn-secondary" %>
          <%= link_to "Edit", edit_product_path(@product), class: "btn btn-secondary" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/exams/edit.html.erb
<div class="no-wrap">
  <div>
    <%= render "shared/sidebar" %>
  </div>
  <div class="contenedor mt-5 vh-100">
    <div class="card mt-5" style="width: 50rem">
      <div class="mb-5">
        <h1>Examen actual</h1>
        <h4>Actualiza los datos para poder llevar un mejor registro de tu Salud</h4>
        <div class="linea"></div>
      </div>
      <div>
        <%= simple_form_for @exam do |f| %>
          <%= f.label :nombre %>
          <%= f.input :name%>

          <%= f.label :fecha%>
          <%= f.input :date %>

          <%= f.label :Lugar %>
          <%= f.input :place%>
          <div class="mt-5">
          <%= f.submit :Crear, class:"btn btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/exams/index.html.erb
<div class="no-wrap">
  <div>
    <%= render "shared/sidebar" %>
  </div>
  <div class="contenedor mt-5">
    <div class="contenedor mt-5 mb-1 vh-100">
    <h1 style="position: absolute;margin-top: -33rem;left: 38rem;">Examenes medicos</h1>
    <div class="card d-flex justify-content-center" style="width: 50rem">
      <div class="row" style="position: relative; right: -13rem;">
        <h3 style="position: relative; left: -13rem;    top: 1rem;">Examenes</h3>
        <%= link_to new_habit_path do %>
          <i class="fa-solid fa-plus icono" style="background-color: #09aea6"></i>
        <% end %>
      </div>
      <div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">FECHA</th>
              <th scope="col">NOMBRE</th>
              <th scope="col">LUGAR</th>
              <th scope="col">ACCIONES</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <% @exams.each do |exam|  %>
            <tr>
              <th scope="row" style="position: relative; text-align: left;"><%= exam.date%></th>
              <th scope="row" style="position: relative; text-align: left;"><%= exam.name%></th>
              <th scope="row" style="position: relative; text-align: left;"><%= exam.place%></th>


              <td><%= link_to exam_path(exam), data: {turbo_method: :delete, turbo_confirm: "Estas seguro que deseas eliminar el examen?"} do %>
              <i class="fa-solid fa-trash" style="color: #f05168"></i>
              <% end %>

              | <%= link_to edit_exam_path(exam) do %>
              <i class="fa-solid fa-pencil" style="color: #ffcc07"></i>
              <% end %>

              | <%= link_to exam_path(exam)do %>
              <i class="fa-solid fa-eye"></i>
              <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

</div>
  </div>
</div>

app/views/exams/new.html.erb
<%= simple_form_for @exam do |f| %>

<%= f.input :date%>
<%= f.input :name %>
<%= f.input :place %>
<%= f.input :photo, as: :file %>
<%= f.submit %>
<% end  %>

app/views/exams/show.html.erb
<%= javascript_include_tag "image_zoom.js" %>
<div class="no-wrap">
    <div>
      <%= render "shared/sidebar" %>
    </div>
  <div class="contenedor-exam">
    <h1 style="position: relative; left: 4rem;">Receta Médica</h1>
  </div>
  <div class="contenedor vh-100">
    <div class="card-exam" style="border: groove;">
      <div class="card-details-exam" style="width: 18rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong style="font-size: 1.5rem">Fecha</strong></li>
          <%= @exam.date %>
          <li class="list-group-item"><strong style="font-size: 1.5rem">Nombre estudio</strong></li>
          <%= @exam.name %>
          <li class="list-group-item"><strong style="font-size: 1.5rem">Lugar Estudio</strong></li>
          <%= @exam.place %>
          <%= link_to "Volver", exams_path(@exams), class: "btn btn-secondary" %>
        </ul>
      </div>
      <div class="img-exam" style="border-radius: 1rem;">
      <%= cl_image_tag @exam.photo.key, id:"my-image", style:"height: 31rem;position:relative;left: -1rem;top: 0rem;"%>
      </div>
    </div>
  </div>
</div>

app/views/habits/edit.html.erb
<div class="no-wrap">
  <div>
    <%= render "shared/sidebar" %>
  </div>
  <div class="contenedor mt-5 vh-100">
    <div class="card mt-5" style="width: 50rem">
      <div class="mb-5">
        <h1>HABITO ACTUAL</h1>
        <h4>Actualiza los datos para poder llevar un mejor registro de tu Salud</h4>
        <div class="linea"></div>
      </div>
      <div>
        <%= simple_form_for @habit do |f| %>
          <%= f.label :Habito %>
          <%= f.select :habit_type, collection: ["Tabaco", "Alcohol", "Café", "Alimentación", "Ejercicio", "Sueño"] %>

          <%= f.label :Cantidad %>
          <%= f.input :quantity %>

          <%= f.label :Frecuencia %>
          <%= f.select :frequency, collection: ["Diario", "Fines de semana", "Habitual", "Ocacional", "Semanal", "Mensual"]%>
          <div class="mt-5">
          <%= f.submit :Crear, class:"btn btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/habits/index.html.erb
<div class="habits-wraper">
  <div>
    <%= render "shared/sidebar" %>
  </div>
  <div class="card-habits-principal ">
    <div class=" card-secundaria-habits">
      <h1 class="titulo-1">Buenos dias, <%= current_user.name %> :</h1>
        <h4 style="display: flex;justify-content: center;font-family: 'Montserrat';font-weight: 300;margin-bottom: -1rem">Estos son tus habitos</h4>
        <div style="display: flex;position: relative;left: 18rem;height: 11rem;">
          <div class="secondary-barra" style="margin-top: 3rem;margin-bottom: 3rem;background-color#: f9f8f8;align-items: center;background: #f9f8f8;border-radius: 60px;justify-content: center;display: flex;    width: 43rem;">
            <div style="margin-right: 2rem;">
              <h4 style="font-size: inherit;color: #6d6e6f;">Hábitos totales : <%= @habits.count %></h4>
            </div>
            <div style="margin-right: 2rem;">
              <h4 style="font-size: inherit;color: #6d6e6f;">Porcentaje Salud : 50%</h4>
            </div>
            <div style="margin-right: 2rem;">
              <h4 style="font-size: inherit;color: #6d6e6f;"> Agregar hábito  </h4>
            </div>
          </div>
        </div>
        <div class="general-card">
          <div class="card-habits">
            <div class="avatar1" style="display: grid;grid-template-columns: 0fr 1fr;border-bottom: inset;height: 7rem;">
              <%= image_tag "healthy-habits", class:"avatar-1", style:"border-radius:50%;height: 5rem;margin-left: 1rem;margin-top: 1rem;"%>
                  <h4 class="card-text-habitos-1"> Tus hábitos</h4>
            </div>
                <div class="table-principal">
                  <table class="table" style="font-weight: 100;font-family: 'Montserrat';;">
                    <thead>
                      <tr>
                        <th scope="col">TIPO</th>
                        <th scope="col">VALOR</th>
                        <th scope="col">FRECUENCIA</th>
                        <th scope="col">ACCIONES</th>
                      </tr>
                    </thead>
                    <tbody class="table-group-divider">
                      <% @habits.each do |habit|  %>
                      <tr>
                        <th scope="row" style="position: relative; text-align: left;"><%= habit.habit_type%></th>
                        <td><%= habit.quantity %></td>
                        <td><%= habit.frequency%></td>

                        <td><%= link_to habit_path(habit), data: {turbo_method: :delete, turbo_confirm: "Estas seguro que deseas eliminar el habito?"} do %>
                        <i class="fa-solid fa-trash" style="color: #f05168"></i>
                        <% end %>

                        | <%= link_to edit_habit_path(habit) do %>
                        <i class="fa-solid fa-pencil" style="color: #ffcc07"></i>
                        <% end %>

                        | <%= link_to habit_path(habit) do %>
                        <i class="fa-solid fa-eye"></i>
                        <% end %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
          </div>
            <div class="card-habits">
              <div class="avatar1" style="display: grid;grid-template-columns: 0fr 1fr;border-bottom: inset;height: 7rem;">
                <%= image_tag "grafico-torta2", class:"avatar-1", style:"border-radius:50%;height: 5rem;margin-left: 1rem;margin-top: 1rem;"%>
                    <h4 class="card-text-habitos-1"> Tus Resultados</h4>
              </div>

            </div>
        </div>
      </div>
  </div>
</div>

app/views/habits/show.html.erb
<div class="no-wrap">
  <div>
    <%= render "shared/sidebar" %>
  </div>
  <div class="contenedor mt-5 vh-100">
    <div class="card mt-5" style="width: 50rem">
      <div class="mt-5 mb-5">
      <h1>HABITO PERSONALIZADO</h1>
      <div class="linea"></div>
    </div>
    <div class="card-body mt-1">
      <h2>Tu habito  <strong><%= @habit.habit_type%></strong></h2>
      <h2>actualmente tiene un valor de  <strong><%= @habit.quantity %></strong></h2>
      <h2>con una frecuencia de <strong><%= @habit.frequency%></strong></h2>
    <div class="mt-5">
      <%= link_to "Volver", habits_path(@habits), class: "btn btn-secondary" %>
    </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="recipes-wraper">
  <div>
    <%= render "shared/sidebar" %>
</div>
  <div class="card-recipes-principal ">
    <div class=" card-secundaria-recipes">
      <h1 class="titulo-1">Buenos dias, <%= current_user.name %> :</h1>
        <h4 style="display: flex;justify-content: center;font-family: 'Montserrat';font-weight: 300;margin-bottom: -1rem">Estas son tus prescripciones</h4>
        <div style="display: flex;height: 11rem; justify-content: center;">
          <div class="secondary-barra" style="margin-top: 3rem;margin-bottom: 3rem;background-color#: f9f8f8;align-items: center;background: #f9f8f8;border-radius: 60px;justify-content: center;display: flex;    width: 43rem;">
            <div style="margin-right: 2rem;">
              <h4 style="font-size: inherit;color: #6d6e6f;">Prescripciones totales : <%= @recipes.count %></h4>
            </div>
            <div style="margin-right: 2rem;">
              <h4 style="font-size: inherit;color: #6d6e6f;">Porcentaje Salud : 50%</h4>
            </div>
            <div style="margin-right: 2rem;">
              <h4 class="link-new-recipe" style="font-size: inherit;color: #6d6e6f;"> <%= link_to "Agregar prescripción", new_recipe_path, style: "font-size: inherit;color: #6d6e6f;" %> </h4>
            </div>
          </div>
        </div>
        <div class="general-card">
          <div class="card-recipes-index">
            <div class="avatar1" style="display: grid;grid-template-columns: 1fr 2fr 1fr;border-bottom: inset;height: 7rem;">
              <%= image_tag "healthy-habits", class:"avatar-1", style:"border-radius:50%;height: 5rem;margin-left: 1rem;margin-top: 1rem;"%>
              <h4 class="card-text-recipes-1"> Tus prescripciones</h4>
              <%= link_to "+", new_recipe_path, style: "text-align: end;display: flex;justify-content: center;margin-top: 0.52rem;font-size: 4rem;" %>
            </div>
                <div class="table-principal">
                  <table class="table" style="font-weight: 100;font-family: 'Montserrat';;">
                    <thead>
                      <tr>
                        <th scope="col">Fecha</th>
                        <th scope="col">Profesional</th>
                        <th scope="col">Acciones</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @recipes.each do |recipe| %>
                      <tr>
                        <th scope="row"><%= recipe.date %></th>
                        <td><%= recipe.doctor_name %></td>
                        <td><%= link_to recipe_path(recipe), data: {turbo_method: :delete, turbo_confirm: "Desea eliminar el elemento de manera permanente?"} do %>
                          <i class="fa-solid fa-trash" style="color: #f05168"></i>
                          <% end %>
                          <%= link_to edit_recipe_path(recipe) do %>
                          <i class="fa-solid fa-pencil" style="color: #ffcc07"></i>
                          <% end %>
                          <%= link_to recipe_path(recipe) do %>
                          <i class="fa-solid fa-eye"></i>
                        <% end %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
            <div class="card-recipes-index">
              <div class="avatar1" style="display: grid;grid-template-columns: 0fr 1fr;border-bottom: inset;height: 7rem;">
                <%= image_tag "icono-recipes", class:"avatar-1", style:"border-radius:50%;height: 5rem;margin-left: 1rem;margin-top: 1rem;"%>
                <h4 class="card-text-recipes-3"> Ultimas prescripciones </h4>
              </div>
              <div class="minicards-principal">
                <% @recipes.first(4).each do |recipe| %>
                  <div class="col">
                        <div class="card-recipes-index">
                          <div class="avatar-2">
                            <%= image_tag "icono-recipes", class:"avatar-1", style:"border-radius:50%;height: 3rem;margin-left: 1rem;margin-top: 1rem;"%>
                            <h3 class="card-text-recipes-4"> <%= recipe.doctor_name %> </h3>
                            <p class="card-text-recipes-5"> <%= recipe.date %> </p>
                          </div>
                        </div>
                  </div>
                <% end %>
              </div>
            </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<h1>Reports Homepage</h1>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright" style="display: contents;">
    <%= link_to "Home", root_path, class: "nav-link px-2 text-muted" %>
    <%= link_to "Nosotros", nosotros_path, class: "nav-link px-2 text-muted" %>
    <%= link_to "Contacto", "#", class: "nav-link px-2 text-muted" %>
  </div>
  <div>
2023 Mi Salud Company, Inc
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "/assets/logo-navbar.png" %>
    <% end %>
    <%= link_to "¿Por que mi salud? ", mi_salud_path , class:"about-us" %>
    <%= link_to "Sobre Nosotros ", nosotros_path, class:"about-us"%>

    <div class="navbar-collapse">
      <ul class="navbar-nav">
          <% if user_signed_in? %>
              <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end">
                <%= link_to "Perfil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Salir", destroy_user_session_path, data: {turbo_method: :delete}, class:  "dropdown-item" %>
              </div>
              <% else %>
               <%= image_tag "alba.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" >
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Salir", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
              <% end %>
          <% else %>
            <li class="nav-item">
              <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link ms-3" %>
            </li>
          <% end %>
        </ul>
    </div>

</div>

app/views/shared/_sidebar.html.erb
<div class="sidenav">
  <div class="menu">
    <h1>
      <button class="btn btn-secondary w-100 btn-sidebar" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="margin-bottom: 1rem;">
        <%= current_user.name %>
      </button>
    </h1>
    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <ul>
          <li> <%= link_to "Mis datos", users_path, class: "dropdown-item collapse-item-datos" %> <li>
          <li> <%= link_to "Cambiar contraseña", edit_user_registration_path, class: "dropdown-item collapse-item" %> <li>
          <li> <%= link_to "Cerrar sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item collapse-item" %> <li>
        </ul>
      </div>
    </div>
    <h1 class="category"> <%= link_to "Mi salud", root_path%> </h1>
    <h1 class="category"> <%= link_to "Turnos", bookings_path%> </h1>
    <h1 class="category"> <%= link_to "Prescripciones", recipes_path%> </h1>
    <h1 class="category"> <%= link_to "Examenes", exams_path%> </h1>
    <h1 class="category"> <%= link_to "Habitos", habits_path%> </h1>
  </div>

  <!-- Page content -->
  <div class="main">
  </div>
</div>